services:
  - type: web
    name: hlc-church-app
    env: node
    plan: free
    rootDir: backend
    buildCommand: ./render-build.sh
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
